package icons;

import com.intellij.openapi.util.IconLoader;
import consulo.ui.image.Image;

/**
 * NOTE THIS FILE IS AUTO-GENERATED by the build/scripts/icons.gant
 * Don't repeat mistakes of others ;-)
 */
public class RegExpSupportIcons {
  private static Image load(String path) {
    return IconLoader.getIcon(path, RegExpSupportIcons.class);
  }

  public static final Image Regexp_filetype_icon = load("/org/intellij/lang/regexp/regexp-filetype-icon.png"); // 11x16
}
